import styles from "./debit.module.css";

export default function DebitCardPage() {
  return (
    <main className={styles.wrapper}>

      {/* HERO */}
      <section className={styles.hero}>
        <div className={styles.card}>
          <div className={styles.topRow}>
            <span className={styles.bank}>CARDVERSE BANK</span>
            <span className={styles.issuer}>VISA / RuPay</span>
          </div>

          <div className={styles.number}>
            4578&nbsp;92XX&nbsp;XXXX&nbsp;1209
          </div>

          <div className={styles.footer}>
            <div>
              <span>Cardholder</span>
              <strong>ROHAN SAKHARE</strong>
            </div>
            <div className={styles.type}>DEBIT</div>
          </div>
        </div>
      </section>

      {/* CONTENT */}
      <section className={styles.content}>

        {/* INTRO */}
        <div className={styles.block}>
          <h2>What is a Debit Card?</h2>
          <p>
            A Debit Card is a payment instrument issued by a bank that allows a
            customer to spend money directly from their linked bank account.
            Unlike credit cards, debit cards do not involve borrowing.
          </p>
          <p>
            Every transaction performed using a debit card results in a
            real-time or near real-time debit of the customer’s account balance.
          </p>
        </div>

        {/* POSITIONING */}
        <div className={styles.block}>
          <h2>Debit Card Positioning</h2>
          <ul>
            <li><strong>Card Type:</strong> Bank Account Linked Card</li>
            <li><strong>Funding Source:</strong> Customer Savings / Current Account</li>
            <li><strong>Spending Limit:</strong> Available Account Balance</li>
            <li><strong>Risk Model:</strong> Low risk (No credit exposure)</li>
          </ul>
        </div>

        {/* ENTITIES */}
        <div className={styles.block}>
          <h2>Entities Involved in Debit Card Ecosystem</h2>
          <ul>
            <li><strong>Cardholder:</strong> Bank customer</li>
            <li><strong>Issuing Bank:</strong> Card issuer & account holder</li>
            <li><strong>Acquirer Bank:</strong> Merchant’s bank</li>
            <li><strong>Payment Network:</strong> Visa / Mastercard / RuPay</li>
            <li><strong>ATM / POS Terminal:</strong> Transaction initiation point</li>
            <li><strong>Core Banking System (CBS):</strong> Balance & ledger system</li>
          </ul>
        </div>

        {/* TYPES */}
        <div className={styles.block}>
          <h2>Types of Debit Cards</h2>
          <ul>
            <li>Domestic Debit Card</li>
            <li>International Debit Card</li>
            <li>Contactless Debit Card</li>
            <li>Virtual Debit Card</li>
            <li>EMV Chip Debit Card</li>
          </ul>
        </div>

        {/* ISSUANCE */}
        <div className={styles.block}>
          <h2>Debit Card Issuance Flow</h2>
          <ol>
            <li>Customer opens bank account</li>
            <li>KYC verification completed</li>
            <li>Debit card generated by issuer</li>
            <li>Card personalized (PAN, expiry, CVV)</li>
            <li>Card dispatched to customer</li>
            <li>Customer activates card via ATM / mobile banking</li>
          </ol>
        </div>

        {/* POS FLOW */}
        <div className={styles.block}>
          <h2>POS Transaction Flow (MOST IMPORTANT)</h2>

          <div className={styles.flow}>
            <span>Cardholder</span>
            <span>POS</span>
            <span>Acquirer</span>
            <span>Network</span>
            <span>Issuer</span>
            <span>CBS</span>
          </div>

          <ol>
            <li>Card tapped/inserted/swiped at POS</li>
            <li>POS sends authorization request to acquirer</li>
            <li>Acquirer routes transaction via network</li>
            <li>Issuer validates card & PIN/EMV data</li>
            <li>CBS checks account balance</li>
            <li>Amount blocked or debited</li>
            <li>Approval returned to merchant</li>
          </ol>
        </div>

        {/* ATM FLOW */}
        <div className={styles.block}>
          <h2>ATM Cash Withdrawal Flow</h2>
          <ol>
            <li>Customer inserts debit card into ATM</li>
            <li>PIN authentication performed</li>
            <li>ATM sends transaction request to issuer</li>
            <li>Issuer validates balance</li>
            <li>Cash dispensed</li>
            <li>Account debited instantly</li>
          </ol>
        </div>

        {/* ONLINE */}
        <div className={styles.block}>
          <h2>Online / E-Commerce Transaction Flow</h2>
          <ol>
            <li>Customer enters card details online</li>
            <li>OTP / 3D Secure authentication</li>
            <li>Network routes request to issuer</li>
            <li>Issuer validates & debits account</li>
            <li>Transaction approved or declined</li>
          </ol>
        </div>

        {/* BALANCE */}
        <div className={styles.block}>
          <h2>Debit Card Balance Model</h2>
          <ul>
            <li>Balance = Bank account balance</li>
            <li>No overdraft by default</li>
            <li>Real-time ledger update</li>
            <li>Immediate fund availability</li>
          </ul>
        </div>

        {/* SECURITY */}
        <div className={styles.block}>
          <h2>Security & Controls</h2>
          <ul>
            <li>PIN based authentication</li>
            <li>EMV chip protection</li>
            <li>Daily ATM & POS limits</li>
            <li>Geographic & channel controls</li>
            <li>Fraud monitoring systems</li>
          </ul>
        </div>

        {/* FAILURES */}
        <div className={styles.block}>
          <h2>Common Failure Scenarios</h2>
          <ul>
            <li>Insufficient balance</li>
            <li>Incorrect PIN</li>
            <li>Card blocked or expired</li>
            <li>Network downtime</li>
          </ul>
        </div>

        {/* SETTLEMENT */}
        <div className={styles.block}>
          <h2>Clearing & Settlement</h2>
          <p>
            Debit card transactions follow a standard clearing and settlement
            cycle where the issuer settles funds with the acquirer through the
            payment network.
          </p>
          <ul>
            <li>T+1 or T+2 settlement</li>
            <li>Issuer debits customer instantly</li>
            <li>Merchant paid post settlement</li>
          </ul>
        </div>

        {/* ADVANTAGES */}
        <div className={styles.block}>
          <h2>Advantages</h2>
          <ul>
            <li>No debt or interest</li>
            <li>Direct control over spending</li>
            <li>Wide acceptance</li>
            <li>Lower fraud risk</li>
          </ul>
        </div>

        {/* LIMITATIONS */}
        <div className={styles.block}>
          <h2>Limitations</h2>
          <ul>
            <li>Limited to available balance</li>
            <li>No credit-building benefit</li>
            <li>Disputes may take longer</li>
          </ul>
        </div>

        {/* SUMMARY */}
        <div className={styles.block}>
          <h2>Summary</h2>
          <p>
            Debit cards are the backbone of everyday digital payments, offering
            secure, real-time access to bank funds while maintaining strong
            control and minimal risk.
          </p>
        </div>

      </section>
    </main>
  );
}
